### ISSUE TITLE
The ant test fails

### ISSUE THREAD

**Issue by nikolay12** [wtsi-npg/illumina2bam#83]
I am thinking of using  https://github.com/wtsi-npg/illumina2bam. I've checked out the code and I've run the ant tests but the build failed:

[junit] Test uk.ac.sanger.npg.picard.SplitBamByReadGroupTest FAILED

I'm not sure whether this is the only test that failed - this was just at the tail of the output. I've tried both the master and the devel branch but the result was the same.

I wonder whether illumina2bam is still usable? It seems that it is under active development. I presume that it is used in production at the Sanger? Would you recommend using it? Basically, I wanted to generate BAM files that contain the read group info.

(sorry for repeating here the email I sent - I did not realise I can open up an issue)

**Comment by dkj** [comment]
Tests work on our machines and on Travis-CI so I suspect your environment is unlike ours. I've no idea if it would work on Windows and I fear that we may have slipped in unix-like environment (e.g. path component separators ```\``` vs ```/```) assumptions. We do use it (heavily) in production though some elements of it have now been usurped by tools from [biobambam2](/gt1/biobambam2). If you're looking to convert bcl files into unaligned bam then I'd recommend you evaluate the functionality provided by modern Picard before resorting to using our tool. Patches to fix your test failures welcome.
